apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: simplemicroservice
replicas: 2
template:
  metadata:
    labels:
      app:  simplemicroservice
spec:
  containers: 
  - name: simplemicroservice
    image:  nagrotte/simplemicroservice:latest
    ports:
    - containerPort: 80 