apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplemicroservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: simplemicroservice
  template:
    metadata:
      labels:
        bb: simplemicroservice
    spec:
      containers:
      - name: simplemicroservice
        image: nagrotte/simplemicroservice:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: simplemicroservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376