apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplemicroservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: simplemicroservice
  template:
    metadata:
      labels:
        bb: simplemicroservice
    spec:
      containers:
      - name: simplemicroservice
        image: nagrotte/simplemicroservice:latest
        ports:
        - containerPort: 80

